#include "jezyk.h"
#include "config.h"
#include <stdio.h>

static const char *const teksty_pl[TEKST_LICZBA_TEKSTOW] =
{
    [TEKST_OK] = "OK",
    [TEKST_WSTECZ] = "Wstecz",
    [TEKST_ANULUJ] = "Anuluj",
    [TEKST_DALEJ] = "Dalej",
    [TEKST_BLAD] = "Błąd",
    [TEKST_OSTRZEZENIE] = "Ostrzeżenie",
    [TEKST_INFORMACJA] = "Informacja",
    [TEKST_BRAK_KARTY_SD] = "Brak karty SD. Ta funkcja wymaga karty pamięci.",
    [TEKST_BRAK_KALIBRACJI] = "Brak wymaganej kalibracji.",
    [TEKST_WYBIERZ_PROFIL_OSL] = "Najpierw wybierz profil kalibracji OSL.",
    [TEKST_KALIBRACJA_OSL_NIEPELNA] = "Kalibracja OSL nie jest kompletna. Zmierz wzorzec niski, środkowy i wysoki.",
    [TEKST_KALIBRACJA_PRZERWANA_BRAK_SYGNALU] = "Kalibracja przerwana. Sygnał pomiarowy jest zbyt słaby lub dane są niewiarygodne. Sprawdź Si5351, 25/27 MHz, zworkę CAL/WORK i tor RF.",
    [TEKST_BRAK_SYGNALU_S21] = "Brak sygnału podczas kalibracji S21. Sprawdź połączenie toru pomiarowego i tłumik kalibracyjny.",
    [TEKST_BLAD_ZAPISU_PLIKU] = "Nie udało się zapisać pliku na karcie SD.",
    [TEKST_BLAD_ODCZYTU_PLIKU] = "Nie udało się odczytać pliku z karty SD.",
    [TEKST_JEZYK] = "Język",
    [TEKST_POLSKI] = "Polski",
    [TEKST_ANGIELSKI] = "English",
    [TEKST_DIAGNOSTYKA] = "Diagnostyka",
    [TEKST_SI5351_NIE_WYKRYTO] = "Nie wykryto generatora Si5351 pod żadnym obsługiwanym adresem.",
    [TEKST_I2C_SPRAWDZ_POLACZENIA] = "Sprawdź zasilanie oraz przewody SDA i SCL.",
    [TEKST_ZAMKNIJ_KOMUNIKAT] = "Dotknij ekranu lub naciśnij OK/Wstecz",
    [TEKST_STATUS_OK] = "OK",
    [TEKST_STATUS_BRAK] = "BRAK",
    [TEKST_KARTA_SD] = "Karta SD",
    [TEKST_ZEGAR_RTC] = "Zegar RTC",
    [TEKST_GENERATOR_SI5351] = "Generator Si5351",
    [TEKST_ADRES_I2C] = "Adres I2C",
    [TEKST_USTAWIENIA_KOLOR_DZWIEK] = "Kolory / dźwięk",
    [TEKST_KONFIGURACJA] = "Konfiguracja",
    [TEKST_KALIBRACJA] = "Kalibracja",
    [TEKST_AKUMULATOR] = "Akumulator",
    [TEKST_DATA_CZAS] = "Data / czas",
    [TEKST_UZYTKOWNIK] = "Użytkownik",
    [TEKST_USB_TRANSFER] = "Transfer USB",
    [TEKST_OBROC_EKRAN] = "Obróć ekran",
    [TEKST_MENU_GLOWNE] = "Menu główne",
    [TEKST_ZMIEN_ZNAK] = "Zmień znak",
    [TEKST_ZNAK] = "Znak:",
    [TEKST_WPISZ_ZNAK] = "Wpisz znak krótkofalarski",
    [TEKST_TRYB_PROSTY] = "Tryb prosty",
    [TEKST_TRYB_ZAAWANSOWANY] = "Tryb zaawansowany",
    [TEKST_CO_CHCESZ_ZROBIC] = "Co chcesz zrobić?",
    [TEKST_POMIAR_ANTENY] = "Pomiar anteny",
    [TEKST_STROJENIE_SWR] = "Strojenie SWR",
    [TEKST_KABEL_TDR] = "Kabel / TDR",
    [TEKST_POMIAR_LC] = "Cewka / kondensator",
    [TEKST_POMIAR_POJEDYNCZY] = "Pomiar pojedynczy",
    [TEKST_PRZEJDZ_ZAAWANSOWANY] = "Tryb zaawansowany",
    [TEKST_MENU_POJEDYNCZY] = "Pojedynczy",
    [TEKST_MENU_WYKRES_SWR] = "Wykres SWR",
    [TEKST_MENU_WIELE_PASM] = "Wiele pasm",
    [TEKST_MENU_STROJENIE] = "Strojenie",
    [TEKST_MENU_S21] = "S21",
    [TEKST_MENU_SZUKAJ_F] = "Skaner RF",
    [TEKST_MENU_KWARC] = "Kwarc",
    [TEKST_MENU_TDR] = "TDR / kabel",
    [TEKST_MENU_LC] = "Elementy RF",
    [TEKST_MENU_DSP] = "DSP",
    [TEKST_MENU_USTAWIENIA] = "Ustawienia",
    [TEKST_MENU_ZRZUTY] = "Zrzuty",
    [TEKST_MENU_USB] = "USB",
    [TEKST_MENU_GENERATOR] = "Generator",
    [TEKST_MENU_CYFROWE] = "WSPR / FT8",
    [TEKST_STROJENIE_TYTUL] = "Strojenie anteny",
    [TEKST_CZESTOTLIWOSC] = "Częstotliwość",
    [TEKST_DZWIEK] = "Dźwięk",
    [TEKST_PROG_SWR_2] = "Próg 2,0",
    [TEKST_PROG_SWR_3] = "Próg 3,0",
    [TEKST_NAJLEPSZY_WYNIK] = "Najlepszy",
    [TEKST_KROK_ENKODERA] = "Krok enkodera",
    [TEKST_OK_ZMIENIA_KROK] = "OK zmienia krok",
    [TEKST_BLISKO_REZONANSU] = "Blisko rezonansu",
    [TEKST_CHARAKTER_INDUKCYJNY] = "charakter indukcyjny",
    [TEKST_CHARAKTER_POJEMNOSCIOWY] = "charakter pojemnościowy",
    [TEKST_INDUKCYJNY_KROTKI] = "Indukcyjny",
    [TEKST_POJEMNOSCIOWY_KROTKI] = "Pojemnościowy",
    [TEKST_BRAK_POMIARU_KROTKI] = "Brak pomiaru",
    [TEKST_OSL_TYTUL_FMT] = "Kalibracja OSL - profil %s",
    [TEKST_OSL_INSTRUKCJA] = "Podłącz wzorzec i naciśnij odpowiedni przycisk.",
    [TEKST_OSL_ZWARCIE_FMT] = "1. Niski: %s",
    [TEKST_OSL_OBCIAZENIE_FMT] = "2. Środkowy: %s",
    [TEKST_OSL_ROZWARCIE_FMT] = "3. Wysoki: %s",
    [TEKST_OSL_ROZWARCIE_NIESKONCZONOSC] = "3. Wysoki: rozwarcie",
    [TEKST_ZAPISZ_I_WYJDZ] = "Zapisz i wyjdź",
    [TEKST_ANULUJ_I_WYJDZ] = "Anuluj i wyjdź",
    [TEKST_HW_CAL_TYTUL] = "Kalibracja sprzętowa",
    [TEKST_HW_CAL_INSTRUKCJA] = "Ustaw zworkę w pozycji kalibracji sprzętowej i naciśnij Start.",
    [TEKST_HW_CAL_START] = "Start kalibracji",
    [TEKST_SUKCES] = "Sukces",
    [TEKST_S21_CAL_TYTUL] = "Kalibracja poziomu S21",
    [TEKST_S21_CAL_INSTRUKCJA] = "Połącz S2 (wyjście generatora) z S1 krótkim przewodem i wykonaj krok 1.",
    [TEKST_S21_CAL_BEZ_TLUMIKA] = "1. Bez tłumika",
    [TEKST_S21_CAL_Z_TLUMIKIEM] = "2. Z tłumikiem",
    [TEKST_S21_CAL_WLOZ_TLUMIK] = "Wstaw fizyczny tłumik 50 om między S2 i S1, potem wykonaj krok 2.",
    [TEKST_S21_CAL_GOTOWE] = "Kalibracja zakończona. Dane zapisano na karcie SD.",
    [TEKST_MENU_KAL_OSL] = "OSL",
    [TEKST_MENU_KAL_HW] = "Kalibracja sprzętowa",
    [TEKST_MENU_KAL_S21] = "Kalibracja S21",
    [TEKST_USB_DOSTEP_PAMIEC] = "Dostęp do karty SD przez port USB HS",
    [TEKST_WYJDZ_RESET] = "Wyjdź (restart urządzenia)",
    [TEKST_EDYTOR_KONFIGURACJI] = "Edytor konfiguracji",
    [TEKST_POPRZEDNI_PARAMETR] = "< Poprzedni",
    [TEKST_NASTEPNY_PARAMETR] = "Następny >",
    [TEKST_ANALIZA] = "Analiza",
    [TEKST_PAMIEC] = "Pamięć",
    [TEKST_TYP_WYKRESU] = "Wykres",
    [TEKST_ZAPISZ_ZRZUT] = "Zrzut",
    [TEKST_AUTO_SZYBKIE] = "Automat",
    [TEKST_SKANUJ] = "Pomiar",
    [TEKST_ZAKRES] = "Zakres",
    [TEKST_WYKRES_SWR_TYTUL] = "Analiza anteny - przebieg",
    [TEKST_TRWA_POMIAR] = "Trwa pomiar...",
    [TEKST_WYKONAJ_POMIAR_NAJPIERW] = "Najpierw wykonaj pomiar przebiegu.",
    [TEKST_ANALIZA_ANTENY] = "Analiza przebiegu anteny",
    [TEKST_MINIMUM_SWR] = "Minimum SWR",
    [TEKST_REZONANS_X0] = "Rezonans X=0",
    [TEKST_PASMO_SWR_15] = "Pasmo SWR < 1,5",
    [TEKST_PASMO_SWR_20] = "Pasmo SWR < 2,0",
    [TEKST_REZONANS_POZA_ZAKRESEM] = "Brak przejścia X przez zero w zmierzonym zakresie.",
    [TEKST_PASMO_POZA_ZAKRESEM] = "Pełne pasmo wykracza poza zmierzony zakres.",
    [TEKST_SWR_POMOC_USTAW_ZAKRES] = "Ustaw częstotliwość i zakres pomiaru",
    [TEKST_SWR_POMOC_ZMIEN_WYKRES] = "Dotknij wykresu, aby zmienić rodzaj prezentacji",
    [TEKST_SWR_POMOC_USTAW_KURSOR] = "Dotknij osi, aby ustawić kursor pomiarowy",
    [TEKST_WCZYTAJ] = "Wczytaj",
    [TEKST_ZAPISZ] = "Zapisz",
    [TEKST_TDR_TYTUL] = "Reflektometr TDR",
    [TEKST_TDR_SKANOWANIE] = "Trwa pomiar TDR...",
    [TEKST_TDR_ZMIEN_VF] = "Zmień Vf",
    [TEKST_TDR_ZAPISZ] = "Zapisz",
    [TEKST_TDR_SKANUJ] = "Pomiar",
    [TEKST_TDR_WARIANT] = "Widok",
    [TEKST_TDR_ZMIEN_VF_TYTUL] = "Zmień współczynnik skrócenia Vf (0...1)",
    [TEKST_TDR_CZAS] = "Czas",
    [TEKST_TDR_AMPLITUDA] = "Odbicie",
    [TEKST_TDR_ODLEGLOSC] = "Odległość",
    [TEKST_TDR_IMPEDANCJA] = "Impedancja",
    [TEKST_TDR_IMPEDANCJA_KABLA] = "Impedancja kabla",
    [TEKST_TDR_WSPOLCZYNNIK_VF] = "Współczynnik Vf",
    [TEKST_TDR_WERYFIKUJ] = "Wyznacz Vf",
    [TEKST_TDR_WERYFIKACJA_TYTUL] = "Weryfikacja długości TDR",
    [TEKST_TDR_DLUGOSC_ZNANA_MM] = "Rzeczywista długość kabla, mm",
    [TEKST_TDR_DLUGOSC_ZMIERZONA] = "Długość z TDR",
    [TEKST_TDR_VF_SUGEROWANE] = "Vf wynikające z długości",
    [TEKST_TDR_ZASTOSUJ_VF] = "Zastosuj Vf",
    [TEKST_TDR_ZAPISZ_VF] = "Zapisz Vf",
    [TEKST_TDR_NAJPIERW_POMIAR] = "Najpierw wykonaj pomiar TDR.",
    [TEKST_TDR_MARKER_KONCA] = "Ustaw kursor na odbiciu końca znanego kabla.",
    [TEKST_TDR_WERYFIKACJA_INFO] = "Jeden punkt koryguje Vf, ale nie oddziela przesunięcia płaszczyzny odniesienia.",
    [TEKST_TDR_JAKOSC] = "Jakość skanu",
    [TEKST_TDR_PUNKTY_POMINIETE] = "Pominięte punkty",
    [TEKST_TDR_IMPEDANCJA_ORIENTACYJNA] = "Z orient. ~",
    [TEKST_ZAPISZ_STALE] = "Zapisz na stałe",
    [TEKST_ZAPISZ_TYMCZASOWO] = "Tylko do wyłączenia",
    [TEKST_POJEDYNCZY_TYTUL] = "Pomiar pojedynczej częstotliwości",
    [TEKST_USTAW_CZESTOTLIWOSC] = "Ustaw częstotliwość",
    [TEKST_ZAPISZ_ZRZUT_EKRANU] = "Zapisz zrzut",
    [TEKST_BRAK_OSL_KROTKI] = "Brak OSL",
    [TEKST_BRAK_SYGNALU_KROTKI] = "Brak sygnału",
    [TEKST_SYGNAL_OK] = "Sygnał OK",
    [TEKST_DOPASOWANIE_LC] = "Dopasowanie LC",
    [TEKST_PRZEJDZ_DOPASOWANIE_LC] = "Dopasuj LC",
    [TEKST_WYKRES_SMITHA] = "Wykres Smitha",
    [TEKST_TON_GENERATORA] = "Ton generatora",
    [TEKST_IMPEDANCJA_SZEREGOWA] = "Impedancja szeregowa",
    [TEKST_IMPEDANCJA_ROWNOLEGLE] = "Impedancja równoległa",
    [TEKST_POZA_ZAKRESEM] = "poza zakresem",
    [TEKST_STRATA_DOPASOWANEGO_KABLA] = "Strata kabla",
    [TEKST_KAL_OSL] = "Kalibracja OSL",
    [TEKST_KAL_SPRZETOWA] = "Kalibracja sprzętowa",
    [TEKST_AKTYWNA] = "aktywna",
    [TEKST_NIEPOPRAWNA] = "niepoprawna",
    [TEKST_BRAK_DOPASOWANIA_LC] = "Brak sensownego dopasowania LC dla tego obciążenia",
    [TEKST_DIAGNOSTYKA_TORU_RF] = "Diagnostyka toru RF",
    [TEKST_SEKCJA_POMIARY] = "POMIARY",
    [TEKST_SEKCJA_NARZEDZIA] = "NARZĘDZIA",
    [TEKST_SEKCJA_USTAWIENIA_GENERATOR] = "USTAWIENIA / GENERATOR",
    [TEKST_GENERATOR_TYTUL] = "Generator RF",
    [TEKST_MOC] = "Moc",
    [TEKST_SYGNAL_SUROWY] = "Sygnał surowy",
    [TEKST_ROZNICA_FAZY] = "Różnica fazy",
    [TEKST_BEZ_KOREKCJI] = "Bez korekcji",
    [TEKST_Z_KOREKCJA_OSL] = "Po korekcji OSL",
    [TEKST_MOC_WYJSCIOWA] = "Moc wyjściowa",
    [TEKST_SI5351_USTAWIENIA] = "Ustawienia Si5351",
    [TEKST_SI5351_ADRES_I2C] = "Adres I2C",
    [TEKST_SI5351_KWARC] = "Kwarc Si5351",
    [TEKST_SI5351_KOREKCJA] = "Korekcja",
    [TEKST_SI5351_REFERENCJA] = "Referencja efektywna",
    [TEKST_SI5351_INNA_WARTOSC] = "Inna...",
    [TEKST_SI5351_WPROWADZ_HZ] = "Częstotliwość kwarcu Si5351 [Hz]",
    [TEKST_SI5351_PO_ZMIANIE_KALIBRUJ] = "Po zmianie: sprawdź 14 MHz, potem HW + OSL.",
    [TEKST_BRAK_SYGNALU_SPRAWDZ_KWARC] = "Kwarc 25/27 MHz? Sprawdź F0/LO",
    [TEKST_BRAK_SYGNALU_SPRAWDZ_I2C] = "Brak Si5351 - sprawdź I2C",
    [TEKST_BRAK_SYGNALU_DIAGNOSTYKA] = "Diagnostyka -> Si5351",
    [TEKST_AKU_NAPIECIE] = "Napięcie",
    [TEKST_AKU_SUROWY_ADC] = "Odczyt ADC",
    [TEKST_AKU_SKALA_ADC] = "Skala ADC",
    [TEKST_AKU_PELNE] = "100% przy",
    [TEKST_AKU_PUSTE] = "0% przy",
    [TEKST_AKU_KALIBRUJ_WOLTOMIERZ] = "Kalibruj wg woltomierza",
    [TEKST_AKU_USTAW_PELNE] = "Ustaw 100%",
    [TEKST_AKU_USTAW_PUSTE] = "Ustaw 0%",
    [TEKST_AKU_WOLTOMIERZ_MV] = "Napięcie z woltomierza [mV], np. 4080",
    [TEKST_AKU_NAPIECIE_PELNE_MV] = "Napięcie 100% [mV]",
    [TEKST_AKU_NAPIECIE_PUSTE_MV] = "Napięcie 0% [mV]",
    [TEKST_AKU_DANE_ADC] = "Dane ADC",
    [TEKST_AKU_ODCZYT] = "Odczyt",
    [TEKST_AKU_SKALA] = "Skala",
    [TEKST_AKU_KALIBRACJA_OK] = "Kalibracja napięcia zapisana",
    [TEKST_AKU_KALIBRACJA_BLAD] = "Nie można skalibrować napięcia. Sprawdź wejście PF9.",
    [TEKST_AKU_WSKAZNIK_WLACZONY] = "Wskaźnik: WŁ.",
    [TEKST_AKU_WSKAZNIK_WYLACZONY] = "Wskaźnik: WYŁ.",
    [TEKST_WYGLAD_DZWIEK] = "Wygląd i dźwięk",
    [TEKST_KOLORY_JASNE] = "Kolory jasne",
    [TEKST_KOLORY_CIEMNE] = "Kolory ciemne",
    [TEKST_GRUBE_LINIE] = "Grube linie",
    [TEKST_CIENKIE_LINIE] = "Cienkie linie",
    [TEKST_DZWIEK_PRZELACZ] = "Dźwięk wł./wył.",
    [TEKST_MOTYW] = "Motyw",
    [TEKST_ZMIEN_MOTYW] = "Zmień motyw",
    [TEKST_WSPR_ZAPISZ_USTAWIENIA] = "Zapisz ustawienia",
    [TEKST_WSPR_NADAWANIE_CIAGLE] = "Nadawanie ciągłe",
    [TEKST_WSPR_NADAJ_RECZNIE] = "Nadaj ręcznie",
    [TEKST_WSPR_NADAJ_RTC] = "Nadaj wg RTC",
    [TEKST_WSPR_POPRZEDNIE_PASMO] = "Poprzednie pasmo",
    [TEKST_WSPR_NASTEPNE_PASMO] = "Następne pasmo",
    [TEKST_WSPR_CZEST_AUDIO] = "Częst. audio",
    [TEKST_WSPR_ZNAK] = "Znak krótkofalarski",
    [TEKST_WSPR_LOKATOR] = "Lokator",
    [TEKST_WSPR_WIADOMOSC] = "Wiadomość FT8 / FT4 / JT",
    [TEKST_WSPR_MOC_TX] = "GEN OUT / S2",
    [TEKST_WSPR_CZAS] = "Czas / do następnego slotu",
    [TEKST_WSPR_TYLKO_WSPR] = "Ta funkcja jest dostępna tylko w trybie WSPR",
    [TEKST_WSPR_PRZEZ_TRX] = "Nadawanie przez radiostację / wyjście audio",
    [TEKST_WSPR_BLAD_TRYBU] = "Nieprawidłowy tryb cyfrowy.",
    [TEKST_WSPR_AUDIO_TYLKO_WSPR] = "Wyjście audio przez radiostację działa tylko w trybie WSPR.",
    [TEKST_WSPR_BLAD_ZNAKU] = "WSPR wymaga standardowego znaku 3-6 znaków, z cyfrą i bez ukośnika.",
    [TEKST_WSPR_BLAD_LOKATORA] = "Lokator WSPR musi mieć 4 znaki, np. JO84.",
    [TEKST_WSPR_BLAD_MOCY] = "Moc WSPR musi być standardowym poziomem 0..60 dBm, np. 0, 3, 7, 10, 13, 17.",
    [TEKST_WSPR_WPISZ_WIADOMOSC] = "Wpisz wiadomość przed nadawaniem.",
    [TEKST_WSPR_LIMIT_FT] = "FT8/FT4: wolny tekst ma najwyżej 13 znaków; do 18 znaków tylko telemetria HEX.",
    [TEKST_WSPR_LIMIT_JT] = "JT65/JT9: wiadomość może mieć najwyżej 13 znaków.",
    [TEKST_WSPR_BRAK_RTC] = "Brak zegara RTC. Nadawanie zsynchronizowane jest zablokowane.",
    [TEKST_WSPR_BLAD_KODERA] = "Koder wiadomości zwrócił nieprawidłowe symbole.",
    [TEKST_WSPR_PROMPT_ZNAK] = "Znak WSPR (maks. 6)",
    [TEKST_WSPR_PROMPT_LOKATOR] = "Lokator 4 znaki",
    [TEKST_WSPR_PROMPT_MOC] = "Moc WSPR 0..60 dBm",
    [TEKST_WSPR_PROMPT_WIADOMOSC] = "Wiadomość: 13 tekst / 18 HEX",
    [TEKST_WSPR_STATUS_GOTOWE] = "Gotowe",
    [TEKST_WSPR_STATUS_CZEKAJ] = "Czekaj...",
    [TEKST_WSPR_STATUS_NADAWANIE] = "Nadawanie",
    [TEKST_WSPR_STATUS_TX] = "Stan nadawania",
    [TEKST_I2C_SKANER] = "Wykrywanie urządzeń I2C",
    [TEKST_I2C_SKANUJ_PONOWNIE] = "Skanuj ponownie",
    [TEKST_I2C_ZNALEZIONO] = "Znalezione urządzenia",
    [TEKST_I2C_NIE_ZNALEZIONO] = "Nie znaleziono urządzeń I2C",
    [TEKST_I2C_NIEZNANE] = "Nieznane urządzenie",
    [TEKST_I2C_ADRES_AKTYWNY] = "aktywny adres Si5351",
    [TEKST_DIAG_KAL_OSL] = "Diagnostyka kalibracji OSL",
    [TEKST_DIAG_PROFIL_OSL] = "Wybrany profil",
    [TEKST_DIAG_PLIK_OSL] = "Plik OSL",
    [TEKST_DIAG_ROZMIAR_PLIKU] = "Rozmiar pliku",
    [TEKST_DIAG_WYMAGANE_MINIMUM] = "Wymagane minimum",
    [TEKST_DIAG_KAL_AKTYWNA] = "Kalibracja OSL",
    [TEKST_DIAG_KOREKCJA_HW] = "Korekcja sprzętowa",
    [TEKST_DIAG_KOREKCJA_S21] = "Korekcja S21",
    [TEKST_DIAG_PRZELADUJ_OSL] = "Przeładuj OSL",
    [TEKST_DIAG_WYNIK_LADOWANIA] = "Wynik ładowania",
    [TEKST_DIAG_ZAKRES_BIEZACY] = "Bieżący zakres",
    [TEKST_DIAG_PLIK_ZA_KROTKI] = "Plik za krótki dla bieżącego zakresu",
    [TEKST_DIAG_BRAK_PROFILU] = "Nie wybrano profilu OSL",
    [TEKST_DIAG_LADOWANIE_OK] = "Plik odczytany poprawnie",
    [TEKST_DIAG_NIE_OTWARTO] = "Nie można otworzyć pliku",
    [TEKST_DIAG_BLAD_ODCZYTU] = "Błąd odczytu pliku",
    [TEKST_DIAG_CZAS_KALIBRACJI] = "Czas kalibracji",
    [TEKST_DIAG_OSL_STARSZA_OD_HW] = "OSL jest starsza od kalibracji HW - wykonaj OSL ponownie.",
    [TEKST_DIAG_KAL_NIEZGODNA_Z_USTAWIENIAMI] = "Kalibracja wykonana dla innych ustawień toru RF.",
    [TEKST_DIAG_HISTORIA_KALIBRACJI] = "Historia kalibracji",
    [TEKST_DIAG_KALIBRACJE_KROTKO] = "Kalibracje",
    [TEKST_POMIAR_METODA_KLASYCZNA] = "Metoda: klasyczna",
    [TEKST_POMIAR_METODA_2026] = "Metoda: 2026",
    [TEKST_POMIAR_DANE_NIEWIARYGODNE] = "Dane pomiarowe niewiarygodne",
    [TEKST_POMIAR_DANE] = "Dane",
    [TEKST_POMIAR_DANE_TYTUL] = "Dane pomiaru",
    [TEKST_POMIAR_PRZED_OSL] = "Przed OSL",
    [TEKST_POMIAR_PO_OSL] = "Po OSL",
    [TEKST_POMIAR_SPOJNOSC_FAZY] = "Spójność fazy",
    [TEKST_POMIAR_ROZRZUT] = "Rozrzut V/I",
    [TEKST_POMIAR_ROZRZUT_INFO] = "Rozrzut opisuje powtarzalność, nie błąd bezwzględny.",
    [TEKST_WERYFIKACJA_WZORCAMI] = "Weryfikacja wzorcami",
    [TEKST_WZORZEC] = "Wzorzec",
    [TEKST_ZMIERZ] = "Zmierz",
    [TEKST_ZAPISZ_CSV] = "Zapisz CSV",
    [TEKST_WYNIK_KLASYCZNY] = "Klasyczna",
    [TEKST_WYNIK_2026] = "2026",
    [TEKST_OCZEKIWANE] = "Oczekiwane",
    [TEKST_WERYFIKACJA_BRAK_WYNIKU] = "Wybierz wzorzec i wykonaj pomiar.",
    [TEKST_WERYFIKACJA_CSV_OK] = "Wynik dopisano do /aa/verify.csv",
    [TEKST_WERYFIKACJA_CSV_BLAD] = "Nie udało się zapisać wyniku CSV.",
    [TEKST_WERYFIKACJA_PASMA] = "Weryfikacja pasma",
    [TEKST_WERYFIKACJA_PASMA_TYTUL] = "Weryfikacja wzorca w paśmie",
    [TEKST_WERYFIKACJA_PASMA_TRWA] = "Trwa pomiar wzorca w całym paśmie...",
    [TEKST_WERYFIKACJA_PASMA_OK] = "Zapisano /aa/vband.csv",
    [TEKST_WERYFIKACJA_PASMA_BLAD] = "Nie udało się wykonać lub zapisać testu pasma.",
    [TEKST_SWR_PUNKTY_POPRAWNE] = "Punkty poprawne",
    [TEKST_SWR_PUNKTY_ODRZUCONE] = "Punkty odrzucone",
    [TEKST_SWR_SKAN_PRZERWANY] = "Skan przerwany - zachowano poprzedni wynik",
    [TEKST_S21_TYTUL] = "S21 - transmisja skalarna",
    [TEKST_S21_SKALARNE_INFO] = "Pomiar modułu |S21|; faza S21 nie jest mierzona.",
    [TEKST_S21_BRAK_KALIBRACJI] = "Brak poprawnej kalibracji poziomu S21",
    [TEKST_SKANER_RF_TYTUL] = "Skaner RF / znajdź sygnał",
    [TEKST_SKANER_RF_OPIS_1] = "Wybierz zakres; Wodospad pokaże sygnały i ich zmiany w czasie.",
    [TEKST_SKANER_RF_OPIS_2] = "Przestraja LO + FFT; nie mierzy SWR ani impedancji.",
    [TEKST_SKANER_RF_CALY_KF] = "KF 0,5-30 MHz",
    [TEKST_SKANER_RF_PASMA_KF] = "Pasma <=30 MHz",
    [TEKST_SKANER_RF_WYBRANY_ZAKRES] = "Skanuj zakres",
    [TEKST_SKANER_RF_WIDMO] = "Wodospad",
    [TEKST_SKANER_RF_AUTO] = "Automat",
    [TEKST_SKANER_RF_BRAK] = "Po skanowaniu zobaczysz widmo i najsilniejszy sygnał",
    [TEKST_SKANER_RF_CZESTOTLIWOSC] = "Częstotliwość sygnału",
    [TEKST_SKANER_RF_POZIOM] = "Poziom orientacyjny",
    [TEKST_SKANER_RF_SZCZYT_TLO] = "Sygnał / tło",
    [TEKST_SKANER_RF_POZIOM_INFO] = "Poziom jest względny; skaner nie jest wzorcowany jako miernik mocy.",
    [TEKST_SKANER_RF_SKANOWANIE] = "Skanowanie...",
    [TEKST_SKANER_RF_ALOKACJA_BLAD] = "Brak pamięci roboczej FFT. Uruchom urządzenie ponownie.",
    [TEKST_KWARC_TYTUL] = "Pomiar kwarcu",
    [TEKST_KWARC_KROK1] = "Krok 1: ustaw przewidywaną częstotliwość rezonansu",
    [TEKST_KWARC_KROK2] = "Krok 2: pozostaw gniazdo puste i skalibruj pojemność uchwytu",
    [TEKST_KWARC_KROK3] = "Krok 3: włóż kwarc i rozpocznij pomiar",
    [TEKST_KWARC_KALIBRUJ_UCHWYT] = "Kalibruj puste gniazdo",
    [TEKST_KWARC_ROZPOCZNIJ] = "Rozpocznij pomiar",
    [TEKST_KWARC_NOWY_POMIAR] = "Nowy pomiar",
    [TEKST_KWARC_KALIBRACJA_OK] = "Kalibracja pojemności uchwytu OK",
    [TEKST_KWARC_KALIBRACJA_BLAD] = "Nie udało się wyznaczyć pojemności pustego uchwytu",
    [TEKST_KWARC_REZONANS_BLAD] = "Nie znaleziono jednoznacznych rezonansów Fs/Fp. Zwiększ zakres lub sprawdź połączenie.",
    [TEKST_KWARC_C0_BLAD] = "Nie udało się wyznaczyć C0 kwarcu. Sprawdź kalibrację pustego uchwytu.",
    [TEKST_KWARC_WYNIK_TYTUL] = "Model zastępczy kwarcu",
    [TEKST_KWARC_METODA_INFO] = "Model BVD: Fs/Fp z interpolacją",
    [TEKST_KWARC_DALEJ] = "Dalej",
    [TEKST_LC_INDUKCYJNOSC] = "Indukcyjność",
    [TEKST_LC_POJEMNOSC] = "Pojemność",
    [TEKST_LC_DANE_POMIARU] = "Dane pomiaru",
    [TEKST_LC_ZMIENNOSC_MODELU_FMT] = "Zmienność modelu: %.2f %%",
    [TEKST_LC_ZMIENNOSC_MODELU_BRAK] = "Zmienność modelu: --",
    [TEKST_LC_ROZNICA_AMPLITUD_FMT] = "Różnica amplitud: %.2f dB",
    [TEKST_LC_BRAK_ZAKRESU_MODELU] = "Brak wiarygodnego zakresu dla modelu L/C",
    [TEKST_LC_BRAK_POMIARU_DSP] = "Brak wiarygodnego pomiaru DSP",
    [TEKST_LC_SONDA_FMT] = "Sonda %s",
    [TEKST_LC_TRYB_L] = "Mierz: L",
    [TEKST_LC_TRYB_C] = "Mierz: C",
    [TEKST_LC_POPRZEDNI_PROFIL] = "Poprz. profil",
    [TEKST_LC_NASTEPNY_PROFIL] = "Nast. profil",
    [TEKST_LC_ZAPISZ_KALIBRACJE] = "Zapisz kal.",
    [TEKST_ZRZUTY_EKRANU] = "Zrzuty ekranu",
    [TEKST_POKAZ] = "Pokaż",
    [TEKST_USUN] = "Usuń",
    [TEKST_POPRZ_STRONA] = "Poprz. strona",
    [TEKST_NAST_STRONA] = "Nast. strona",
    [TEKST_BRAK_ZAPISANYCH_ZRZUTOW] = "Brak zapisanych zrzutów ekranu",
    [TEKST_NAZWA] = "Nazwa",
    [TEKST_DATA] = "Data",
    [TEKST_CZAS] = "Czas",
    [TEKST_DZIEN] = "Dzień",
    [TEKST_MIESIAC] = "Miesiąc",
    [TEKST_ROK] = "Rok",
    [TEKST_GODZINA] = "Godzina",
    [TEKST_MINUTA] = "Minuta",
    [TEKST_DATA_CZAS_POMOC] = "Enkoder: zmiana   OK: dalej / zapisz   Wstecz: anuluj",
    [TEKST_ROZMIAR] = "Rozmiar",
    [TEKST_GENERATOR_CZESTOTLIWOSC] = "Generator RF - częstotliwość",
    [TEKST_GENERATOR_WYJSCIE] = "Generator RF - wyjście i modulacja",
    [TEKST_GENERATOR_DIAGNOSTYKA] = "Generator RF - diagnostyka",
    [TEKST_GENERATOR_KROK_STROJENIA] = "Krok strojenia",
    [TEKST_GENERATOR_GOTOWE_MHZ] = "Gotowe MHz",
    [TEKST_GENERATOR_WPISZ_CZESTOTLIWOSC] = "Wpisz częstotliwość",
    [TEKST_GENERATOR_POWROT] = "Powrót do generatora",
    [TEKST_GENERATOR_MODULACJA] = "Modulacja",
    [TEKST_GENERATOR_NOSNA] = "Nośna",
    [TEKST_GENERATOR_NIEFILTROWANE] = "Wyjście jest niefiltrowane.",
    [TEKST_GENERATOR_FILTR_ZALECANY] = "Zalecane filtrowanie zewnętrzne.",
    [TEKST_GENERATOR_STAN] = "Stan generatora",
    [TEKST_GENERATOR_SPRAWDZ] = "SPRAWDŹ",
    [TEKST_GENERATOR_HARMONICZNA] = "harmoniczna",
    [TEKST_GENERATOR_POZIOM_S2] = "Poziom S2",
    [TEKST_GENERATOR_WYJSCIE_S2] = "GEN OUT / S2",
    [TEKST_GENERATOR_POZIOM_NIESKALIBROWANY] = "Poziom harmonicznej nieskalibrowany; wyjście niefiltrowane.",
    [TEKST_GENERATOR_POZA_ZAKRESEM] = "Poza zakresem generatora",
    [TEKST_USTAWIENIA_WYGLAD_OBSLUGA] = "Wygląd i obsługa",
    [TEKST_USTAWIENIA_URZADZENIE_PROFIL] = "Urządzenie i profil",
    [TEKST_USTAWIENIA_ZAAWANSOWANE] = "Zaawansowane",
    [TEKST_DIAG_STAN_METROLOGICZNY] = "Stan metrologiczny",
    [TEKST_DIAG_RAPORT] = "Raport",
    [TEKST_DIAG_RAPORT_OK] = "Raport zapisano w /aa/diag",
    [TEKST_DIAG_RAPORT_BLAD] = "Nie udało się zapisać raportu diagnostycznego.",
    [TEKST_DIAG_DORADCZA] = "Diagnostyka doradcza; ! = sprawdź raport. Nie blokuje pomiarów.",
    [TEKST_DIAG_BRAK_META] = "brak metadanych",
    [TEKST_DIAG_BRAK_RTC] = "brak wiarygodnego czasu RTC",
    [TEKST_DIAG_STARY_FORMAT] = "starszy format metadanych",
    [TEKST_DIAG_KONFIGURACJA] = "inne ustawienia toru RF",
    [TEKST_DIAG_BRAK_PLIKU] = "brak pliku współczynników",
    [TEKST_DIAG_PLIK_ZMIENIONY] = "plik współczynników został zmieniony",
    [TEKST_DIAG_HW_ZMIENIONE] = "kalibracja HW została zmieniona później",
    [TEKST_DIAG_RTC_COFNIETY] = "RTC wskazuje czas wcześniejszy niż kalibracja",
    [TEKST_WSPR_DOTKNIJ_ABY_WPISAC] = "Dotknij pola, aby wpisać wiadomość",
    [TEKST_O_PROGRAMIE] = "O programie",
    [TEKST_TWORCY_I_WKLAD] = "Twórcy i wkład",
    [TEKST_O_PROGRAMIE_ROZWINIECIE] = "Rozwinięcie otwartego projektu analizatora EU1KY",
    [TEKST_WKLAD_AUTOR_PROJEKTU] = "autor projektu",
    [TEKST_WKLAD_ROZWOJ_FIRMWARE] = "rozwój firmware",
    [TEKST_WKLAD_ROZSZERZENIA_CEC] = "CEC: L/C, S21, cyfrowe",
    [TEKST_WKLAD_EU1KY_PL] = "PL: testy i rozwój",
    [TEKST_WKLAD_DOKUMENTACJA] = "instrukcje społeczności",
    [TEKST_O_PROGRAMIE_DZIEKUJEMY] = "Dziękujemy wszystkim, którzy rozwijali i testowali ten analizator.",
    [TEKST_NIEMIECKI] = "Deutsch",
    [TEKST_HISZPANSKI] = "",
    [TEKST_ROSYJSKI] = "Русский",
    [TEKST_JAPONSKI] = "",
    [TEKST_PODTYTUL_ANALIZATOR_ANTENOWY] = "Analizator antenowy",
    [TEKST_PRZYGOTOWANIE_FUNKCJI] = "Przygotowanie funkcji...",
    [TEKST_METROLOGIA_2026_TEST] = "Metrologia 2026 - TEST",
    [TEKST_DZIAL_POMIAR] = "Pomiar",
    [TEKST_DZIAL_ANALIZA] = "Analiza",
    [TEKST_DZIAL_NARZEDZIA] = "Narzędzia",
    [TEKST_DZIAL_KALIBRACJA] = "Kalibracja",
    [TEKST_DZIAL_USTAWIENIA] = "Ustawienia",
    [TEKST_DZIAL_PLIKI] = "Pliki",
    [TEKST_MENU_DSP_AUDIO] = "DSP audio",
    [TEKST_MENU_DEKODER_CW] = "Dekoder CW",
    [TEKST_MENU_STAN_KALIBRACJI] = "Stan kalibracji",
    [TEKST_MENU_SERWIS] = "Serwis",
    [TEKST_MENU_MENEDZER_PLIKOW] = "Menedżer plików",
    [TEKST_REZERWA_HISTORYCZNA_01] = "",
    [TEKST_MENU_WZORCE_DC] = "Dokładne wzorce z miernika",
    [TEKST_MENU_PROJEKTOWANIE_ANTEN] = "Projektowanie anten",
    [TEKST_MENU_LACZNOSC_VNA] = "Łączność / VNA",
    [TEKST_MENU_PROFIL_SPRZETU] = "Profil sprzętowy",
    [TEKST_MENU_GENERATOR_INSTRUKCJI] = "Automat zrzutów",
    [TEKST_MENU_ZRZUTY_UZUPELNIENIA] = "Uzupełnij zrzuty",
    [TEKST_MENU_CENTRUM_KALIBRACJI] = "Centrum kalibracji",
    [TEKST_MENU_KAL_LC] = "Kalibracja L/C",
    [TEKST_POZIOM_FUNKCJI] = "Poziom funkcji",
    [TEKST_KONFIGURACJA_ZAAWANSOWANA] = "Konfiguracja zaawansowana",
    [TEKST_STYL_INTERFEJSU] = "Styl interfejsu",
};

static const char *const teksty_en[TEKST_LICZBA_TEKSTOW] =
{
    [TEKST_OK] = "OK",
    [TEKST_WSTECZ] = "Back",
    [TEKST_ANULUJ] = "Cancel",
    [TEKST_DALEJ] = "Next",
    [TEKST_BLAD] = "Error",
    [TEKST_OSTRZEZENIE] = "Warning",
    [TEKST_INFORMACJA] = "Information",
    [TEKST_BRAK_KARTY_SD] = "No SD card. This function requires a memory card.",
    [TEKST_BRAK_KALIBRACJI] = "Required calibration is missing.",
    [TEKST_WYBIERZ_PROFIL_OSL] = "Select an OSL calibration profile first.",
    [TEKST_KALIBRACJA_OSL_NIEPELNA] = "OSL calibration is incomplete. Measure the low, middle and high standards first.",
    [TEKST_KALIBRACJA_PRZERWANA_BRAK_SYGNALU] = "Calibration stopped. The measurement signal is too weak or the data is unreliable. Check Si5351, 25/27 MHz, CAL/WORK jumper and RF path.",
    [TEKST_BRAK_SYGNALU_S21] = "No signal during S21 calibration. Check the measurement path and calibration attenuator.",
    [TEKST_BLAD_ZAPISU_PLIKU] = "Could not write the file to the SD card.",
    [TEKST_BLAD_ODCZYTU_PLIKU] = "Could not read the file from the SD card.",
    [TEKST_JEZYK] = "Language",
    [TEKST_POLSKI] = "Polski",
    [TEKST_ANGIELSKI] = "English",
    [TEKST_DIAGNOSTYKA] = "Diagnostics",
    [TEKST_SI5351_NIE_WYKRYTO] = "Si5351 was not detected at any supported address.",
    [TEKST_I2C_SPRAWDZ_POLACZENIA] = "Check power and the SDA/SCL connections.",
    [TEKST_ZAMKNIJ_KOMUNIKAT] = "Touch the screen or press OK/Back",
    [TEKST_STATUS_OK] = "OK",
    [TEKST_STATUS_BRAK] = "MISSING",
    [TEKST_KARTA_SD] = "SD card",
    [TEKST_ZEGAR_RTC] = "RTC clock",
    [TEKST_GENERATOR_SI5351] = "Si5351 generator",
    [TEKST_ADRES_I2C] = "I2C address",
    [TEKST_USTAWIENIA_KOLOR_DZWIEK] = "Colours / beep",
    [TEKST_KONFIGURACJA] = "Configuration",
    [TEKST_KALIBRACJA] = "Calibration",
    [TEKST_AKUMULATOR] = "Battery settings",
    [TEKST_DATA_CZAS] = "Date / time",
    [TEKST_UZYTKOWNIK] = "User",
    [TEKST_USB_TRANSFER] = "USB transfer",
    [TEKST_OBROC_EKRAN] = "Flip screen",
    [TEKST_MENU_GLOWNE] = "Main menu",
    [TEKST_ZMIEN_ZNAK] = "Change callsign",
    [TEKST_ZNAK] = "Callsign:",
    [TEKST_WPISZ_ZNAK] = "Enter amateur radio callsign",
    [TEKST_TRYB_PROSTY] = "Simple mode",
    [TEKST_TRYB_ZAAWANSOWANY] = "Advanced mode",
    [TEKST_CO_CHCESZ_ZROBIC] = "What do you want to do?",
    [TEKST_POMIAR_ANTENY] = "Antenna sweep",
    [TEKST_STROJENIE_SWR] = "Tune SWR",
    [TEKST_KABEL_TDR] = "Cable / TDR",
    [TEKST_POMIAR_LC] = "Inductor / capacitor",
    [TEKST_POMIAR_POJEDYNCZY] = "Single measurement",
    [TEKST_PRZEJDZ_ZAAWANSOWANY] = "Advanced mode",
    [TEKST_MENU_POJEDYNCZY] = "Single",
    [TEKST_MENU_WYKRES_SWR] = "SWR sweep",
    [TEKST_MENU_WIELE_PASM] = "Multi SWR",
    [TEKST_MENU_STROJENIE] = "Tune SWR",
    [TEKST_MENU_S21] = "S21",
    [TEKST_MENU_SZUKAJ_F] = "RF scanner",
    [TEKST_MENU_KWARC] = "Quartz",
    [TEKST_MENU_TDR] = "TDR / cable",
    [TEKST_MENU_LC] = "RF components",
    [TEKST_MENU_DSP] = "DSP",
    [TEKST_MENU_USTAWIENIA] = "Settings",
    [TEKST_MENU_ZRZUTY] = "Snapshots",
    [TEKST_MENU_USB] = "USB",
    [TEKST_MENU_GENERATOR] = "Generator",
    [TEKST_MENU_CYFROWE] = "WSPR / FT8",
    [TEKST_STROJENIE_TYTUL] = "Antenna tuning",
    [TEKST_CZESTOTLIWOSC] = "Frequency",
    [TEKST_DZWIEK] = "Tone",
    [TEKST_PROG_SWR_2] = "Limit 2.0",
    [TEKST_PROG_SWR_3] = "Limit 3.0",
    [TEKST_NAJLEPSZY_WYNIK] = "Best",
    [TEKST_KROK_ENKODERA] = "Encoder step",
    [TEKST_OK_ZMIENIA_KROK] = "OK changes step",
    [TEKST_BLISKO_REZONANSU] = "Near resonance",
    [TEKST_CHARAKTER_INDUKCYJNY] = "inductive",
    [TEKST_CHARAKTER_POJEMNOSCIOWY] = "capacitive",
    [TEKST_INDUKCYJNY_KROTKI] = "Inductive",
    [TEKST_POJEMNOSCIOWY_KROTKI] = "Capacitive",
    [TEKST_BRAK_POMIARU_KROTKI] = "No measurement",
    [TEKST_OSL_TYTUL_FMT] = "OSL calibration - profile %s",
    [TEKST_OSL_INSTRUKCJA] = "Connect a standard and press the corresponding button.",
    [TEKST_OSL_ZWARCIE_FMT] = "1. Low: %s",
    [TEKST_OSL_OBCIAZENIE_FMT] = "2. Middle: %s",
    [TEKST_OSL_ROZWARCIE_FMT] = "3. High: %s",
    [TEKST_OSL_ROZWARCIE_NIESKONCZONOSC] = "3. High: open circuit",
    [TEKST_ZAPISZ_I_WYJDZ] = "Save and exit",
    [TEKST_ANULUJ_I_WYJDZ] = "Cancel and exit",
    [TEKST_HW_CAL_TYTUL] = "Hardware calibration",
    [TEKST_HW_CAL_INSTRUKCJA] = "Set the jumper to the hardware calibration position and press Start.",
    [TEKST_HW_CAL_START] = "Start calibration",
    [TEKST_SUKCES] = "Success",
    [TEKST_S21_CAL_TYTUL] = "S21 level calibration",
    [TEKST_S21_CAL_INSTRUKCJA] = "Connect S2 (generator output) to S1 with a short coax cable and perform step 1.",
    [TEKST_S21_CAL_BEZ_TLUMIKA] = "1. Without attenuator",
    [TEKST_S21_CAL_Z_TLUMIKIEM] = "2. With attenuator",
    [TEKST_S21_CAL_WLOZ_TLUMIK] = "Insert a physical 50-ohm attenuator between S2 and S1, then perform step 2.",
    [TEKST_S21_CAL_GOTOWE] = "Calibration complete. Data were saved to the SD card.",
    [TEKST_MENU_KAL_HW] = "Hardware calibration",
    [TEKST_USB_DOSTEP_PAMIEC] = "SD card access through USB HS port",
    [TEKST_WYJDZ_RESET] = "Exit (restart device)",
    [TEKST_EDYTOR_KONFIGURACJI] = "Configuration editor",
    [TEKST_POPRZEDNI_PARAMETR] = "< Previous",
    [TEKST_NASTEPNY_PARAMETR] = "Next >",
    [TEKST_ANALIZA] = "Analysis",
    [TEKST_PAMIEC] = "Memory",
    [TEKST_TYP_WYKRESU] = "Plot",
    [TEKST_ZAPISZ_ZRZUT] = "Snapshot",
    [TEKST_AUTO_SZYBKIE] = "Auto fast",
    [TEKST_SKANUJ] = "Scan",
    [TEKST_ZAKRES] = "Range",
    [TEKST_WYKRES_SWR_TYTUL] = "Antenna analysis - sweep",
    [TEKST_TRWA_POMIAR] = "Measuring...",
    [TEKST_WYKONAJ_POMIAR_NAJPIERW] = "Run a sweep measurement first.",
    [TEKST_ANALIZA_ANTENY] = "Antenna sweep analysis",
    [TEKST_MINIMUM_SWR] = "Minimum SWR",
    [TEKST_REZONANS_X0] = "Resonance X=0",
    [TEKST_PASMO_SWR_15] = "Bandwidth SWR < 1.5",
    [TEKST_PASMO_SWR_20] = "Bandwidth SWR < 2.0",
    [TEKST_REZONANS_POZA_ZAKRESEM] = "No X zero crossing in the measured range.",
    [TEKST_PASMO_POZA_ZAKRESEM] = "The full bandwidth extends beyond the measured range.",
    [TEKST_SWR_POMOC_USTAW_ZAKRES] = "Set measurement frequency and span",
    [TEKST_SWR_POMOC_ZMIEN_WYKRES] = "Tap the plot to change presentation type",
    [TEKST_SWR_POMOC_USTAW_KURSOR] = "Tap the axis to set the measurement cursor",
    [TEKST_WCZYTAJ] = "Load",
    [TEKST_ZAPISZ] = "Save",
    [TEKST_TDR_TYTUL] = "TDR reflectometer",
    [TEKST_TDR_SKANOWANIE] = "TDR measurement...",
    [TEKST_TDR_ZMIEN_VF] = "Change Vf",
    [TEKST_TDR_ZAPISZ] = "Save",
    [TEKST_TDR_SKANUJ] = "Scan",
    [TEKST_TDR_WARIANT] = "View",
    [TEKST_TDR_ZMIEN_VF_TYTUL] = "Change velocity factor Vf (0...1)",
    [TEKST_TDR_CZAS] = "Time",
    [TEKST_TDR_AMPLITUDA] = "Reflection",
    [TEKST_TDR_ODLEGLOSC] = "Distance",
    [TEKST_TDR_IMPEDANCJA] = "Impedance",
    [TEKST_TDR_IMPEDANCJA_KABLA] = "Cable impedance",
    [TEKST_TDR_WSPOLCZYNNIK_VF] = "Velocity factor Vf",
    [TEKST_TDR_WERYFIKUJ] = "Find Vf",
    [TEKST_TDR_WERYFIKACJA_TYTUL] = "TDR length verification",
    [TEKST_TDR_DLUGOSC_ZNANA_MM] = "Known cable length, mm",
    [TEKST_TDR_DLUGOSC_ZMIERZONA] = "TDR length",
    [TEKST_TDR_VF_SUGEROWANE] = "Vf from known length",
    [TEKST_TDR_ZASTOSUJ_VF] = "Apply Vf",
    [TEKST_TDR_ZAPISZ_VF] = "Save Vf",
    [TEKST_TDR_NAJPIERW_POMIAR] = "Run a TDR measurement first.",
    [TEKST_TDR_MARKER_KONCA] = "Place the cursor on the reflection from the known cable end.",
    [TEKST_TDR_WERYFIKACJA_INFO] = "One point corrects Vf but cannot separate reference-plane offset.",
    [TEKST_TDR_JAKOSC] = "Scan quality",
    [TEKST_TDR_PUNKTY_POMINIETE] = "Skipped points",
    [TEKST_TDR_IMPEDANCJA_ORIENTACYJNA] = "Approx. Z ~",
    [TEKST_ZAPISZ_STALE] = "Store permanently",
    [TEKST_ZAPISZ_TYMCZASOWO] = "Store until power off",
    [TEKST_POJEDYNCZY_TYTUL] = "Single frequency measurement",
    [TEKST_USTAW_CZESTOTLIWOSC] = "Set frequency",
    [TEKST_ZAPISZ_ZRZUT_EKRANU] = "Save snapshot",
    [TEKST_BRAK_OSL_KROTKI] = "No OSL",
    [TEKST_BRAK_SYGNALU_KROTKI] = "No signal",
    [TEKST_SYGNAL_OK] = "Signal OK",
    [TEKST_DOPASOWANIE_LC] = "LC matching",
    [TEKST_PRZEJDZ_DOPASOWANIE_LC] = "LC match",
    [TEKST_WYKRES_SMITHA] = "Smith chart",
    [TEKST_TON_GENERATORA] = "Generator tone",
    [TEKST_IMPEDANCJA_SZEREGOWA] = "Series impedance",
    [TEKST_IMPEDANCJA_ROWNOLEGLE] = "Parallel impedance",
    [TEKST_POZA_ZAKRESEM] = "out of range",
    [TEKST_STRATA_DOPASOWANEGO_KABLA] = "Cable loss",
    [TEKST_KAL_OSL] = "OSL calibration",
    [TEKST_KAL_SPRZETOWA] = "Hardware calibration",
    [TEKST_AKTYWNA] = "active",
    [TEKST_NIEPOPRAWNA] = "invalid",
    [TEKST_BRAK_DOPASOWANIA_LC] = "No useful LC match for this load",
    [TEKST_DIAGNOSTYKA_TORU_RF] = "RF path diagnostics",
    [TEKST_SEKCJA_POMIARY] = "MEASUREMENT",
    [TEKST_SEKCJA_NARZEDZIA] = "TOOLS",
    [TEKST_SEKCJA_USTAWIENIA_GENERATOR] = "SETTINGS / SIGNAL GENERATOR",
    [TEKST_GENERATOR_TYTUL] = "RF generator",
    [TEKST_MOC] = "Power",
    [TEKST_SYGNAL_SUROWY] = "Raw signal",
    [TEKST_ROZNICA_FAZY] = "Phase difference",
    [TEKST_BEZ_KOREKCJI] = "Uncorrected",
    [TEKST_Z_KOREKCJA_OSL] = "With OSL correction",
    [TEKST_MOC_WYJSCIOWA] = "Output power",
    [TEKST_SI5351_USTAWIENIA] = "Si5351 settings",
    [TEKST_SI5351_ADRES_I2C] = "I2C address",
    [TEKST_SI5351_KWARC] = "Si5351 crystal",
    [TEKST_SI5351_KOREKCJA] = "Correction",
    [TEKST_SI5351_REFERENCJA] = "Effective reference",
    [TEKST_SI5351_INNA_WARTOSC] = "Other...",
    [TEKST_SI5351_WPROWADZ_HZ] = "Si5351 crystal frequency [Hz]",
    [TEKST_SI5351_PO_ZMIANIE_KALIBRUJ] = "After change: verify 14 MHz, then repeat HW + OSL.",
    [TEKST_BRAK_SYGNALU_SPRAWDZ_KWARC] = "25/27 MHz crystal? Check F0/LO",
    [TEKST_BRAK_SYGNALU_SPRAWDZ_I2C] = "No Si5351 - check I2C",
    [TEKST_BRAK_SYGNALU_DIAGNOSTYKA] = "Diagnostics -> Si5351",
    [TEKST_AKU_NAPIECIE] = "Voltage",
    [TEKST_AKU_SUROWY_ADC] = "ADC reading",
    [TEKST_AKU_SKALA_ADC] = "ADC scale",
    [TEKST_AKU_PELNE] = "100% at",
    [TEKST_AKU_PUSTE] = "0% at",
    [TEKST_AKU_KALIBRUJ_WOLTOMIERZ] = "Calibrate to voltmeter",
    [TEKST_AKU_USTAW_PELNE] = "Set 100%",
    [TEKST_AKU_USTAW_PUSTE] = "Set 0%",
    [TEKST_AKU_WOLTOMIERZ_MV] = "Voltmeter value [mV], e.g. 4080",
    [TEKST_AKU_NAPIECIE_PELNE_MV] = "100% voltage [mV]",
    [TEKST_AKU_NAPIECIE_PUSTE_MV] = "0% voltage [mV]",
    [TEKST_AKU_DANE_ADC] = "ADC data",
    [TEKST_AKU_ODCZYT] = "Reading",
    [TEKST_AKU_SKALA] = "Scale",
    [TEKST_AKU_KALIBRACJA_OK] = "Voltage calibration saved",
    [TEKST_AKU_KALIBRACJA_BLAD] = "Voltage calibration failed. Check PF9 input.",
    [TEKST_AKU_WSKAZNIK_WLACZONY] = "Indicator: ON",
    [TEKST_AKU_WSKAZNIK_WYLACZONY] = "Indicator: OFF",
    [TEKST_WYGLAD_DZWIEK] = "Appearance and sound",
    [TEKST_KOLORY_JASNE] = "Daylight colours",
    [TEKST_KOLORY_CIEMNE] = "Indoor colours",
    [TEKST_GRUBE_LINIE] = "Thick lines",
    [TEKST_CIENKIE_LINIE] = "Thin lines",
    [TEKST_DZWIEK_PRZELACZ] = "Sound on/off",
    [TEKST_MOTYW] = "Theme",
    [TEKST_ZMIEN_MOTYW] = "Change theme",
    [TEKST_WSPR_ZAPISZ_USTAWIENIA] = "Save settings",
    [TEKST_WSPR_NADAWANIE_CIAGLE] = "Continuous TX",
    [TEKST_WSPR_NADAJ_RECZNIE] = "Manual TX",
    [TEKST_WSPR_NADAJ_RTC] = "RTC TX",
    [TEKST_WSPR_POPRZEDNIE_PASMO] = "Previous band",
    [TEKST_WSPR_NASTEPNE_PASMO] = "Next band",
    [TEKST_WSPR_CZEST_AUDIO] = "Audio frequency",
    [TEKST_WSPR_ZNAK] = "Callsign",
    [TEKST_WSPR_LOKATOR] = "Locator",
    [TEKST_WSPR_WIADOMOSC] = "FT8 / FT4 / JT message",
    [TEKST_WSPR_MOC_TX] = "GEN OUT / S2",
    [TEKST_WSPR_CZAS] = "Device time / next slot",
    [TEKST_WSPR_TYLKO_WSPR] = "This function is available in WSPR mode only",
    [TEKST_WSPR_PRZEZ_TRX] = "Transmit via transceiver / audio output",
    [TEKST_WSPR_BLAD_TRYBU] = "Invalid digital mode.",
    [TEKST_WSPR_AUDIO_TYLKO_WSPR] = "Audio via transceiver is available in WSPR mode only.",
    [TEKST_WSPR_BLAD_ZNAKU] = "WSPR requires a standard 3-6 character callsign with a digit and no slash.",
    [TEKST_WSPR_BLAD_LOKATORA] = "WSPR locator must have 4 characters, e.g. JO84.",
    [TEKST_WSPR_BLAD_MOCY] = "WSPR power must use a standard 0..60 dBm level, e.g. 0, 3, 7, 10, 13, 17.",
    [TEKST_WSPR_WPISZ_WIADOMOSC] = "Enter a message before transmitting.",
    [TEKST_WSPR_LIMIT_FT] = "FT8/FT4: free text is limited to 13 characters; up to 18 only for HEX telemetry.",
    [TEKST_WSPR_LIMIT_JT] = "JT65/JT9: message is limited to 13 characters.",
    [TEKST_WSPR_BRAK_RTC] = "RTC is not available. Synchronized transmission is blocked.",
    [TEKST_WSPR_BLAD_KODERA] = "The message encoder returned invalid symbols.",
    [TEKST_WSPR_PROMPT_ZNAK] = "WSPR callsign (max 6)",
    [TEKST_WSPR_PROMPT_LOKATOR] = "4-char locator",
    [TEKST_WSPR_PROMPT_MOC] = "WSPR power 0..60 dBm",
    [TEKST_WSPR_PROMPT_WIADOMOSC] = "Message: 13 text / 18 HEX",
    [TEKST_WSPR_STATUS_GOTOWE] = "Ready",
    [TEKST_WSPR_STATUS_CZEKAJ] = "Wait...",
    [TEKST_WSPR_STATUS_NADAWANIE] = "On air",
    [TEKST_WSPR_STATUS_TX] = "Transmission status",
    [TEKST_I2C_SKANER] = "I2C device detection",
    [TEKST_I2C_SKANUJ_PONOWNIE] = "Scan again",
    [TEKST_I2C_ZNALEZIONO] = "Detected devices",
    [TEKST_I2C_NIE_ZNALEZIONO] = "No I2C devices found",
    [TEKST_I2C_NIEZNANE] = "Unknown device",
    [TEKST_I2C_ADRES_AKTYWNY] = "active Si5351 address",
    [TEKST_DIAG_KAL_OSL] = "OSL calibration diagnostics",
    [TEKST_DIAG_PROFIL_OSL] = "Selected profile",
    [TEKST_DIAG_PLIK_OSL] = "OSL file",
    [TEKST_DIAG_ROZMIAR_PLIKU] = "File size",
    [TEKST_DIAG_WYMAGANE_MINIMUM] = "Minimum required",
    [TEKST_DIAG_KAL_AKTYWNA] = "OSL calibration",
    [TEKST_DIAG_KOREKCJA_HW] = "Hardware correction",
    [TEKST_DIAG_KOREKCJA_S21] = "S21 correction",
    [TEKST_DIAG_PRZELADUJ_OSL] = "Reload OSL",
    [TEKST_DIAG_WYNIK_LADOWANIA] = "Load result",
    [TEKST_DIAG_ZAKRES_BIEZACY] = "Current range",
    [TEKST_DIAG_PLIK_ZA_KROTKI] = "File is too short for current range",
    [TEKST_DIAG_BRAK_PROFILU] = "No OSL profile selected",
    [TEKST_DIAG_LADOWANIE_OK] = "File loaded correctly",
    [TEKST_DIAG_NIE_OTWARTO] = "Could not open file",
    [TEKST_DIAG_BLAD_ODCZYTU] = "File read error",
    [TEKST_DIAG_CZAS_KALIBRACJI] = "Calibration time",
    [TEKST_DIAG_OSL_STARSZA_OD_HW] = "OSL is older than hardware calibration - repeat OSL.",
    [TEKST_DIAG_KAL_NIEZGODNA_Z_USTAWIENIAMI] = "Calibration was made with different RF settings.",
    [TEKST_DIAG_HISTORIA_KALIBRACJI] = "Calibration history",
    [TEKST_DIAG_KALIBRACJE_KROTKO] = "Calibrations",
    [TEKST_POMIAR_METODA_KLASYCZNA] = "Method: classic",
    [TEKST_POMIAR_METODA_2026] = "Method: 2026",
    [TEKST_POMIAR_DANE_NIEWIARYGODNE] = "Measurement data unreliable",
    [TEKST_POMIAR_DANE] = "Data",
    [TEKST_POMIAR_DANE_TYTUL] = "Measurement data",
    [TEKST_POMIAR_PRZED_OSL] = "Before OSL",
    [TEKST_POMIAR_PO_OSL] = "After OSL",
    [TEKST_POMIAR_SPOJNOSC_FAZY] = "Phase coherence",
    [TEKST_POMIAR_ROZRZUT] = "V/I spread",
    [TEKST_POMIAR_ROZRZUT_INFO] = "Spread describes repeatability, not absolute error.",
    [TEKST_WERYFIKACJA_WZORCAMI] = "Verification with standards",
    [TEKST_WZORZEC] = "Standard",
    [TEKST_ZMIERZ] = "Measure",
    [TEKST_ZAPISZ_CSV] = "Save CSV",
    [TEKST_WYNIK_KLASYCZNY] = "Classic",
    [TEKST_WYNIK_2026] = "2026",
    [TEKST_OCZEKIWANE] = "Expected",
    [TEKST_WERYFIKACJA_BRAK_WYNIKU] = "Select a standard and run the measurement.",
    [TEKST_WERYFIKACJA_CSV_OK] = "Result appended to /aa/verify.csv",
    [TEKST_WERYFIKACJA_CSV_BLAD] = "Could not save the CSV result.",
    [TEKST_WERYFIKACJA_PASMA] = "Band verification",
    [TEKST_WERYFIKACJA_PASMA_TYTUL] = "Standard verification across band",
    [TEKST_WERYFIKACJA_PASMA_TRWA] = "Measuring the standard across the band...",
    [TEKST_WERYFIKACJA_PASMA_OK] = "Saved /aa/vband.csv",
    [TEKST_WERYFIKACJA_PASMA_BLAD] = "Could not complete or save the band verification.",
    [TEKST_SWR_PUNKTY_POPRAWNE] = "Valid points",
    [TEKST_SWR_PUNKTY_ODRZUCONE] = "Rejected points",
    [TEKST_SWR_SKAN_PRZERWANY] = "Scan cancelled - previous result kept",
    [TEKST_S21_TYTUL] = "S21 - scalar transmission",
    [TEKST_S21_SKALARNE_INFO] = "Magnitude |S21| only; S21 phase is not measured.",
    [TEKST_S21_BRAK_KALIBRACJI] = "No valid S21 level calibration",
    [TEKST_SKANER_RF_TYTUL] = "RF scanner / find signal",
    [TEKST_SKANER_RF_OPIS_1] = "Select a range; Waterfall shows signals and their changes over time.",
    [TEKST_SKANER_RF_OPIS_2] = "Sweeps LO + FFT; it does not measure SWR or impedance.",
    [TEKST_SKANER_RF_CALY_KF] = "HF 0.5-30 MHz",
    [TEKST_SKANER_RF_PASMA_KF] = "Ham bands <=30 MHz",
    [TEKST_SKANER_RF_WYBRANY_ZAKRES] = "Scan range",
    [TEKST_SKANER_RF_WIDMO] = "Waterfall",
    [TEKST_SKANER_RF_AUTO] = "Auto",
    [TEKST_SKANER_RF_BRAK] = "After scanning you will see the spectrum and strongest signal",
    [TEKST_SKANER_RF_CZESTOTLIWOSC] = "Signal frequency",
    [TEKST_SKANER_RF_POZIOM] = "Approximate level",
    [TEKST_SKANER_RF_SZCZYT_TLO] = "Signal / background",
    [TEKST_SKANER_RF_POZIOM_INFO] = "The level is relative; the scanner is not calibrated as a power meter.",
    [TEKST_SKANER_RF_SKANOWANIE] = "Scanning...",
    [TEKST_SKANER_RF_ALOKACJA_BLAD] = "FFT working memory is unavailable. Restart the device.",
    [TEKST_KWARC_TYTUL] = "Quartz measurement",
    [TEKST_KWARC_KROK1] = "Step 1: set the expected resonance frequency",
    [TEKST_KWARC_KROK2] = "Step 2: leave the fixture open and calibrate its capacitance",
    [TEKST_KWARC_KROK3] = "Step 3: insert the crystal and start measurement",
    [TEKST_KWARC_KALIBRUJ_UCHWYT] = "Calibrate open fixture",
    [TEKST_KWARC_ROZPOCZNIJ] = "Start measurement",
    [TEKST_KWARC_NOWY_POMIAR] = "New measurement",
    [TEKST_KWARC_KALIBRACJA_OK] = "Fixture capacitance calibration OK",
    [TEKST_KWARC_KALIBRACJA_BLAD] = "Could not determine open-fixture capacitance",
    [TEKST_KWARC_REZONANS_BLAD] = "No unambiguous Fs/Fp resonance pair. Increase span or check the connection.",
    [TEKST_KWARC_C0_BLAD] = "Could not determine crystal C0. Check the open-fixture calibration.",
    [TEKST_KWARC_WYNIK_TYTUL] = "Quartz equivalent model",
    [TEKST_KWARC_METODA_INFO] = "BVD model: interpolated Fs/Fp",
    [TEKST_KWARC_DALEJ] = "Continue",
    [TEKST_LC_INDUKCYJNOSC] = "Inductance",
    [TEKST_LC_POJEMNOSC] = "Capacitance",
    [TEKST_LC_DANE_POMIARU] = "Measurement data",
    [TEKST_LC_ZMIENNOSC_MODELU_FMT] = "Model variation: %.2f %%",
    [TEKST_LC_ZMIENNOSC_MODELU_BRAK] = "Model variation: --",
    [TEKST_LC_ROZNICA_AMPLITUD_FMT] = "Magnitude difference: %.2f dB",
    [TEKST_LC_BRAK_ZAKRESU_MODELU] = "No reliable range for L/C model",
    [TEKST_LC_BRAK_POMIARU_DSP] = "No reliable DSP measurement",
    [TEKST_LC_SONDA_FMT] = "Probe %s",
    [TEKST_LC_TRYB_L] = "Mode: L",
    [TEKST_LC_TRYB_C] = "Mode: C",
    [TEKST_LC_POPRZEDNI_PROFIL] = "Prev. probe",
    [TEKST_LC_NASTEPNY_PROFIL] = "Next probe",
    [TEKST_LC_ZAPISZ_KALIBRACJE] = "Save cal.",
    [TEKST_ZRZUTY_EKRANU] = "Screenshots",
    [TEKST_POKAZ] = "Show",
    [TEKST_USUN] = "Delete",
    [TEKST_POPRZ_STRONA] = "Prev. page",
    [TEKST_NAST_STRONA] = "Next page",
    [TEKST_BRAK_ZAPISANYCH_ZRZUTOW] = "No saved screenshots",
    [TEKST_NAZWA] = "Name",
    [TEKST_DATA] = "Date",
    [TEKST_CZAS] = "Time",
    [TEKST_DZIEN] = "Day",
    [TEKST_MIESIAC] = "Month",
    [TEKST_ROK] = "Year",
    [TEKST_GODZINA] = "Hour",
    [TEKST_MINUTA] = "Minute",
    [TEKST_DATA_CZAS_POMOC] = "Encoder: change   OK: next / save   Back: cancel",
    [TEKST_ROZMIAR] = "Size",
    [TEKST_GENERATOR_CZESTOTLIWOSC] = "RF generator - frequency",
    [TEKST_GENERATOR_WYJSCIE] = "RF generator - output / modulation",
    [TEKST_GENERATOR_DIAGNOSTYKA] = "RF generator - diagnostics",
    [TEKST_GENERATOR_KROK_STROJENIA] = "Tuning step",
    [TEKST_GENERATOR_GOTOWE_MHZ] = "Presets MHz",
    [TEKST_GENERATOR_WPISZ_CZESTOTLIWOSC] = "Enter frequency",
    [TEKST_GENERATOR_POWROT] = "Back to generator",
    [TEKST_GENERATOR_MODULACJA] = "Modulation",
    [TEKST_GENERATOR_NOSNA] = "Carrier",
    [TEKST_GENERATOR_NIEFILTROWANE] = "Output is unfiltered.",
    [TEKST_GENERATOR_FILTR_ZALECANY] = "External filtering is recommended.",
    [TEKST_GENERATOR_STAN] = "Generator status",
    [TEKST_GENERATOR_SPRAWDZ] = "CHECK",
    [TEKST_GENERATOR_HARMONICZNA] = "harmonic",
    [TEKST_GENERATOR_POZIOM_S2] = "S2 level",
    [TEKST_GENERATOR_WYJSCIE_S2] = "GEN OUT / S2",
    [TEKST_GENERATOR_POZIOM_NIESKALIBROWANY] = "Harmonic level is uncalibrated; output is not filtered.",
    [TEKST_GENERATOR_POZA_ZAKRESEM] = "Outside generator range",
    [TEKST_USTAWIENIA_WYGLAD_OBSLUGA] = "Appearance and controls",
    [TEKST_USTAWIENIA_URZADZENIE_PROFIL] = "Device and profile",
    [TEKST_USTAWIENIA_ZAAWANSOWANE] = "Advanced",
    [TEKST_DIAG_STAN_METROLOGICZNY] = "Metrology status",
    [TEKST_DIAG_RAPORT] = "Report",
    [TEKST_DIAG_RAPORT_OK] = "Report saved in /aa/diag",
    [TEKST_DIAG_RAPORT_BLAD] = "Could not save the diagnostic report.",
    [TEKST_DIAG_DORADCZA] = "Advisory diagnostics; ! = see report. Measurements remain available.",
    [TEKST_DIAG_BRAK_META] = "metadata unavailable",
    [TEKST_DIAG_BRAK_RTC] = "reliable RTC time unavailable",
    [TEKST_DIAG_STARY_FORMAT] = "older metadata format",
    [TEKST_DIAG_KONFIGURACJA] = "different RF configuration",
    [TEKST_DIAG_BRAK_PLIKU] = "coefficient file missing",
    [TEKST_DIAG_PLIK_ZMIENIONY] = "coefficient file changed",
    [TEKST_DIAG_HW_ZMIENIONE] = "HW calibration changed afterwards",
    [TEKST_DIAG_RTC_COFNIETY] = "RTC is earlier than calibration time",
    [TEKST_WSPR_DOTKNIJ_ABY_WPISAC] = "Tap the field to enter a message",
    [TEKST_O_PROGRAMIE] = "About",
    [TEKST_TWORCY_I_WKLAD] = "Authors and contributions",
    [TEKST_O_PROGRAMIE_ROZWINIECIE] = "A continuation of the open EU1KY antenna analyzer project",
    [TEKST_WKLAD_AUTOR_PROJEKTU] = "project author",
    [TEKST_WKLAD_ROZWOJ_FIRMWARE] = "firmware development",
    [TEKST_WKLAD_ROZSZERZENIA_CEC] = "CEC: L/C, S21, digital",
    [TEKST_WKLAD_EU1KY_PL] = "PL: tests and development",
    [TEKST_WKLAD_DOKUMENTACJA] = "community manuals",
    [TEKST_O_PROGRAMIE_DZIEKUJEMY] = "Thank you to everyone who developed and tested this analyzer.",
    [TEKST_NIEMIECKI] = "Deutsch",
    [TEKST_HISZPANSKI] = "",
    [TEKST_ROSYJSKI] = "Русский",
    [TEKST_JAPONSKI] = "",
    [TEKST_PODTYTUL_ANALIZATOR_ANTENOWY] = "Antenna analyzer",
    [TEKST_PRZYGOTOWANIE_FUNKCJI] = "Preparing function...",
    [TEKST_METROLOGIA_2026_TEST] = "Metrology 2026 - TEST",
    [TEKST_DZIAL_POMIAR] = "Measure",
    [TEKST_DZIAL_ANALIZA] = "Analysis",
    [TEKST_DZIAL_NARZEDZIA] = "Tools",
    [TEKST_DZIAL_KALIBRACJA] = "Calibration",
    [TEKST_DZIAL_USTAWIENIA] = "Settings",
    [TEKST_DZIAL_PLIKI] = "Files",
    [TEKST_MENU_DSP_AUDIO] = "Audio DSP",
    [TEKST_MENU_DEKODER_CW] = "CW decoder",
    [TEKST_MENU_STAN_KALIBRACJI] = "Calibration status",
    [TEKST_MENU_SERWIS] = "Service",
    [TEKST_MENU_MENEDZER_PLIKOW] = "File manager",
    [TEKST_REZERWA_HISTORYCZNA_01] = "",
    [TEKST_MENU_WZORCE_DC] = "Exact standards from meter",
    [TEKST_MENU_PROJEKTOWANIE_ANTEN] = "Antenna design",
    [TEKST_MENU_LACZNOSC_VNA] = "Connectivity / VNA",
    [TEKST_MENU_PROFIL_SPRZETU] = "Hardware profile",
    [TEKST_MENU_GENERATOR_INSTRUKCJI] = "Auto screenshots",
    [TEKST_MENU_ZRZUTY_UZUPELNIENIA] = "Missing screens",
    [TEKST_MENU_CENTRUM_KALIBRACJI] = "Calibration center",
    [TEKST_MENU_KAL_LC] = "L/C calibration",
    [TEKST_POZIOM_FUNKCJI] = "Feature level",
    [TEKST_KONFIGURACJA_ZAAWANSOWANA] = "Advanced configuration",
    [TEKST_STYL_INTERFEJSU] = "Interface style",
};

static const char *const teksty_de[TEKST_LICZBA_TEKSTOW] =
{
#include "jezyk_de.inc"
};


static const char *const teksty_ru[TEKST_LICZBA_TEKSTOW] =
{
#include "jezyk_ru.inc"
};


static int32_t jezyk_tymczasowy = -1;

static uint8_t JEZYK_CzyObslugiwany(JEZYK_t jezyk)
{
    return (jezyk == JEZYK_POLSKI || jezyk == JEZYK_ANGIELSKI ||
            jezyk == JEZYK_NIEMIECKI || jezyk == JEZYK_ROSYJSKI) ? 1U : 0U;
}

JEZYK_t JEZYK_Aktualny(void)
{
    uint32_t wartosc;

    /*
     * Wartosci 3 (dawny ES) i 5 (dawny JP) moga pozostac w config.bin po
     * aktualizacji starszego firmware. Nie przesuwamy numeru rosyjskiego 4,
     * tylko bezpiecznie wracamy do polskiego.
     */
    if (jezyk_tymczasowy >= 0 &&
        JEZYK_CzyObslugiwany((JEZYK_t)jezyk_tymczasowy))
        return (JEZYK_t)jezyk_tymczasowy;

    wartosc = CFG_GetParam(CFG_PARAM_JEZYK);
    if (wartosc < (uint32_t)JEZYK_WARTOSC_GRANICZNA &&
        JEZYK_CzyObslugiwany((JEZYK_t)wartosc))
        return (JEZYK_t)wartosc;

    return JEZYK_POLSKI;
}

void JEZYK_UstawTymczasowy(JEZYK_t jezyk)
{
    if (JEZYK_CzyObslugiwany(jezyk))
        jezyk_tymczasowy = (int32_t)jezyk;
}

void JEZYK_WyczyscTymczasowy(void)
{
    jezyk_tymczasowy = -1;
}

const char *JEZYK_Nazwa(JEZYK_t jezyk)
{
    switch (jezyk)
    {
    case JEZYK_ANGIELSKI: return "English";
    case JEZYK_NIEMIECKI: return "Deutsch";
    case JEZYK_ROSYJSKI: return "Русский";
    case JEZYK_POLSKI:
    default: return "Polski";
    }
}

const char *JEZYK_KodProjektu(void)
{
    switch (JEZYK_Aktualny())
    {
    case JEZYK_ANGIELSKI: return "EN";
    case JEZYK_NIEMIECKI: return "DE";
    case JEZYK_ROSYJSKI: return "RU";
    case JEZYK_POLSKI:
    default: return "PL";
    }
}

void JEZYK_FormatujNazweProjektu(char *bufor, size_t rozmiar)
{
    if (bufor == 0 || rozmiar == 0U)
        return;

    snprintf(bufor, rozmiar, "EU1KY-%s 2026", JEZYK_KodProjektu());
}

const char *JEZYK_Wybierz(const char *pl, const char *en, const char *de, const char *ru)
{
    const char *tekst;

    switch (JEZYK_Aktualny())
    {
    case JEZYK_ANGIELSKI: tekst = en; break;
    case JEZYK_NIEMIECKI: tekst = de; break;
    case JEZYK_ROSYJSKI: tekst = ru; break;
    case JEZYK_POLSKI:
    default: tekst = pl; break;
    }

    if (tekst == 0 || tekst[0] == '\0')
        tekst = (en != 0 && en[0] != '\0') ? en : pl;
    return tekst != 0 ? tekst : "?";
}

uint8_t JEZYK_CzySeparatorDziesietnyPrzecinek(void)
{
    return JEZYK_Aktualny() == JEZYK_ANGIELSKI ? 0U : 1U;
}

const char *JEZYK_Tekst(TEKST_ID_t id)
{
    const char *tekst = 0;

    if ((uint32_t)id >= (uint32_t)TEKST_LICZBA_TEKSTOW)
        return "?";

    switch (JEZYK_Aktualny())
    {
    case JEZYK_ANGIELSKI: tekst = teksty_en[id]; break;
    case JEZYK_NIEMIECKI: tekst = teksty_de[id]; break;
    case JEZYK_ROSYJSKI: tekst = teksty_ru[id]; break;
    case JEZYK_POLSKI:
    default: tekst = teksty_pl[id]; break;
    }

    /*
     * Diagnostyczny bezpiecznik na przyszłość: nowo dopisany identyfikator nie
     * może powodować pustego pola. Angielski jest neutralnym fallbackiem, a
     * kompletność tablic pilnują testy hostowe przed wydaniem firmware.
     */
    if (tekst == 0 || tekst[0] == '\0')
        tekst = teksty_en[id];
    return (tekst != 0 && tekst[0] != '\0') ? tekst : "?";
}

