#ifndef _DIAGNOSTYKA_H_
#define _DIAGNOSTYKA_H_

#include <stdint.h>

void DIAGNOSTYKA_Otworz(void);
void DIAGNOSTYKA_OtworzSi5351(void);
uint8_t DIAGNOSTYKA_OtworzSprawdzenieIF(void);
void DIAGNOSTYKA_OtworzStanMetrologiczny(void);
void DIAGNOSTYKA_OtworzSD(void);

typedef enum
{
    DIAGNOSTYKA_RAPORT_BLAD_BRAK_SD = 1UL << 0,
    DIAGNOSTYKA_RAPORT_BLAD_SCIEZKA = 1UL << 1,
    DIAGNOSTYKA_RAPORT_BLAD_OTWARCIE = 1UL << 2,
    DIAGNOSTYKA_RAPORT_BLAD_NAGLOWEK = 1UL << 3,
    DIAGNOSTYKA_RAPORT_BLAD_RTC = 1UL << 4,
    DIAGNOSTYKA_RAPORT_BLAD_PASMO = 1UL << 5,
    DIAGNOSTYKA_RAPORT_BLAD_SYNTEZA = 1UL << 6,
    DIAGNOSTYKA_RAPORT_BLAD_SYSTEM = 1UL << 7,
    DIAGNOSTYKA_RAPORT_BLAD_SPRAWDZENIE_IF = 1UL << 9,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_HW = 1UL << 10,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_OSL = 1UL << 11,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_S21 = 1UL << 12,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_LC = 1UL << 13,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_TDR = 1UL << 14,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_BATERIA = 1UL << 15,
    DIAGNOSTYKA_RAPORT_BLAD_KAL_KWARC = 1UL << 16,
    DIAGNOSTYKA_RAPORT_BLAD_SYNCHRONIZACJA = 1UL << 17,
    DIAGNOSTYKA_RAPORT_BLAD_ZAMKNIECIE = 1UL << 18,
    DIAGNOSTYKA_RAPORT_BLAD_PODMIANA = 1UL << 19
} DIAGNOSTYKA_RAPORT_BLAD_t;

/* Zapisuje doradczy raport diagnostyczny. Błąd raportu nigdy nie blokuje pomiarów. */
int DIAGNOSTYKA_ZapiszRaport(void);
int DIAGNOSTYKA_ZapiszRaportDo(const char *sciezka_docelowa);
uint32_t DIAGNOSTYKA_OstatnieBledyRaportu(void);

#endif
