#ifndef IKONY_SZCZEGOLOWE_DODATKOWE_H_
#define IKONY_SZCZEGOLOWE_DODATKOWE_H_

#include <stdint.h>
#include "ikony_szczegolowe_makiety.h"

enum
{
    UI_IKONA_DOD_WYGLAD_OBSLUGA = 0,
    UI_IKONA_DOD_POMOC_JEZYK = 1,
    UI_IKONA_DOD_METODY_POZIOM = 2,
    UI_IKONA_DOD_KWARC_CZAS = 3,
    UI_IKONA_DOD_AKUMULATOR = 4,
    UI_IKONA_DOD_URZADZENIE = 5,
    UI_IKONA_DOD_KALIBRACJA = 6,
    UI_IKONA_DOD_GENERATOR = 7,
    UI_IKONA_DOD_CYFROWE = 8,
    UI_IKONA_DOD_DEKODER_CW = 9,
    UI_IKONA_DOD_DSP = 10,
    UI_IKONA_DOD_PROJEKTOWANIE_ANTEN = 11
};

#define UI_IKONY_SZCZEGOLOWE_DODATKOWE_LICZBA 12U

extern const UI_IKONA_SZCZEGOLOWA_t ui_ikony_szczegolowe_dodatkowe[UI_IKONY_SZCZEGOLOWE_DODATKOWE_LICZBA];

#endif
